apiVersion: v2
name: directus
type: application

description: |
  A Helm chart for installing Directus on Kubernetes.
  Directus is a real-time API and App dashboard for managing SQL database content.

home: https://directus.io/

sources:
  - https://github.com/zjpiazza/directus-helm-chart
  - https://github.com/directus/directus

icon: https://avatars.githubusercontent.com/u/79210894

maintainers:
  - name: zjpiazza
    url: https://github.com/zjpiazza/directus-helm-chart

version: 2.2.0
appVersion: "11.9.3"

dependencies:
- name: mysql
  version: "~13.0.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mysql.enabled
- name: postgresql
  version: "~16.7.8"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
- name: redis
  version: "~21.1.11"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled

