{{- if and (not .Values.postgresql.external.enabled) .Values.postgresql.enabled (or .Values.secrets.createDatabase .Values.createPostgresqlSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret | default (printf "%s-postgresql" .Release.Name) }}
  labels:
    app.kubernetes.io/name: {{ include "directus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "directus.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  postgres-password: {{ randAlphaNum 16 | b64enc | quote }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  replication-password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
