{{- if and .Values.mysql.enabled (or .Values.secrets.createDatabase .Values.createMysqlSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.auth.existingSecret | default (printf "%s-mysql" .Release.Name) }}
  labels:
    app.kubernetes.io/name: {{ include "directus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "directus.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  mysql-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  mysql-replication-password: {{ randAlphaNum 16 | b64enc | quote }}
  mysql-password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
